// frontend/src/components/Header.vue
<script setup lang="ts">

</script>

<template>
  <header>
    <nav class="bg-blue-500 p-4">
      <div class="container mx-auto flex justify-between items-center">
        <div class="text-white text-xl font-semibold">
          CrossBoxFit
        </div>
        <ul class="flex space-x-4">
          <li><RouterLink to="/" class="text-white hover:text-gray-300 hover:underline">Home</RouterLink></li>
          <li><RouterLink to="/about" class="text-white hover:text-gray-300 hover:underline">About</RouterLink></li>
        </ul>
      </div>
    </nav>
  </header>
</template>

<style scoped>

</style>

// frontend/src/components/Header.tsx
import { Link } from "react-router-dom";

const Header: React.FC = () => {
    return (
			<>
				<div className="w-full bg-gray-50 border-b border-b-gray-200">
        <div className="w-full max-w-6xl mx-auto px-3 md:px-12 py-5 flex flex-row justify-between items-center">
          <div className="flex flex-row justify-start items-center shrink mr-2">
            <Link to="/" className="text-lg cursor-pointer flex flex-row justify-start items-center">
              CrossBoxFit
            </Link>
          </div>
          <div className="relative flex-shrink-0">
          </div>
        </div>
      </div>
			</>
    );
}

export default Header;
